import { IDataForStudentCard } from "@/components/LessonStudentCard";

export const dataForStudentCard: IDataForStudentCard[] = [
    {
      id: 1,
      name: "Кравцов А.Д.",
      missedTotal: 999,
      reasonedMissedTotal: 0,
      attendanceRatePecentage: 13,
      allDisciplinesAttendanceRate: 56,
      allDisciplinesMissedTotal: 20,
    },
    {
      id: 2,
      name: "Кравцов А.Д.",
      missedTotal: 999,
      reasonedMissedTotal: 0,
      attendanceRatePecentage: 13,
      allDisciplinesAttendanceRate: 56,
      allDisciplinesMissedTotal: 20,
    },
    {
      id: 3,
      name: "Кравцов А.Д.",
      missedTotal: 999,
      reasonedMissedTotal: 0,
      attendanceRatePecentage: 13,
      allDisciplinesAttendanceRate: 56,
      allDisciplinesMissedTotal: 20,
    },
    {
        id: 4,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
      {
        id: 5,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
      {
        id: 6,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
      {
        id: 7,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
      {
        id: 8,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
      {
        id: 9,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
      {
        id: 10,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
      {
        id: 11,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
      {
        id: 12,
        name: "Кравцов А.Д.",
        missedTotal: 999,
        reasonedMissedTotal: 0,
        attendanceRatePecentage: 13,
        allDisciplinesAttendanceRate: 56,
        allDisciplinesMissedTotal: 20,
      },
  ];